version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"          # или 5433:5432, если локальный 5432 занят
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: